### ISSUE TITLE
Feat: react化の最中にvue側で開発・反映されたものをreactに持っていく

### ISSUE THREAD

**Issue by ichi-h** [Wizleap-Inc/wiz-ui#941]
**機能追加理由・詳細**

- [x] #950
- [x] #952
- [x] #954
- [x] #953
- [x] #956
- [x] #955
- [x] #957
- [x] #958
- [x] #965
- [x] #985
- [x] #989
- [x] #994
- [x] #1009
- [x] #1043

**解決策の提案（任意）**

**その他考慮事項（任意）**

**Comment by wmoai** [comment]
React 版に入っていないリスト
* https://github.com/Wizleap-Inc/wiz-ui/pull/667
* https://github.com/Wizleap-Inc/wiz-ui/pull/699
  * https://github.com/Wizleap-Inc/wiz-ui/pull/825
  * https://github.com/Wizleap-Inc/wiz-ui/pull/836
  * https://github.com/Wizleap-Inc/wiz-ui/pull/918
* https://github.com/Wizleap-Inc/wiz-ui/pull/761
* https://github.com/Wizleap-Inc/wiz-ui/pull/777
* https://github.com/Wizleap-Inc/wiz-ui/pull/790
* https://github.com/Wizleap-Inc/wiz-ui/pull/820
*

**Comment by ichi-h** [comment]
- [ ] 「Popup で影が残るバグを修正」のreact対応 #667
- [ ] 「Fix/fixed popup」のreact対応 #699
- [ ] 「fix(popup): fixedの要素上でpopupが追従しない問題を解消」のreact対応 #825
- [ ] 「Fix(popup): fixedされたpopupの位置計算にスクロール量が算入される」のreact対応 #836
- [ ] 「Feat(popup): sticky対応」のreact対応 #918
- [ ] 「ToggleSwitch に default color を設定」のreact対応 #761
- [ ] 「Add a hideClose prop in dialog」のreact対応 #777
- [ ] 「ラジオボタンの a11y 対応 」のreact対応 #790
- [ ] 「Feat(menu-item): fontSizeプロパティを追加」のreact対応 #820
